services:
  postgres:
    image: postgres:16-alpine
    container_name: rahanna-postgres
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - default
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rahanna:
    image: ghcr.io/boozec/rahanna-api:latest
    container_name: rahanna-api
    networks:
      - default
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_TOKEN=${JWT_TOKEN}
      - API_ADDRESS=:8080
      - DEBUG=0
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: unless-stopped

networks:
  default:

volumes:
  postgres_data:
