version: 2

project_name: rahanna

before:
  hooks:
    - go mod tidy

builds:
  - id: api
    main: ./cmd/api/main.go
    binary: rahanna-api
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
  - id: ui
    main: ./cmd/ui/main.go
    binary: rahanna-ui
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - id: api-archive
    name_template: >-
      {{ .ProjectName }}_api_{{ .Os }}_{{ .Arch }}
    builds:
      - api
    format_overrides:
      - goos: windows
        formats:
          - zip
  - id: ui-archive
    name_template: >-
      {{ .ProjectName }}_ui_{{ .Os }}_{{ .Arch }}
    builds:
      - ui
    format_overrides:
      - goos: windows
        formats:
          - zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  footer: |
    ---
    Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
